# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class AssetDetails(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type: str=None, value: str=None):
        """
        AssetDetails - a model defined in Swagger

        :param type: The type of this AssetDetails.
        :type type: str
        :param value: The value of this AssetDetails.
        :type value: str
        """
        self.swagger_types = {
            'type': str,
            'value': str
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value'
        }

        self._type = type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'AssetDetails':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The assetDetails of this AssetDetails.
        :rtype: AssetDetails
        """
        return deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """
        Gets the type of this AssetDetails.
        Key of the asset detail

        :return: The type of this AssetDetails.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """
        Sets the type of this AssetDetails.
        Key of the asset detail

        :param type: The type of this AssetDetails.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def value(self) -> str:
        """
        Gets the value of this AssetDetails.
        Value of the asset detail

        :return: The value of this AssetDetails.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """
        Sets the value of this AssetDetails.
        Value of the asset detail

        :param value: The value of this AssetDetails.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value

